### ISSUE TITLE
Dose all 10000 points of every objects in Modelnet40_normal_resampled dataset are used as the input?

### ISSUE THREAD

**Issue by LiJin73** [Gofinge/PointTransformerV2#13]
Thank you for your great job. But I have seen the code and the config in Issue #9, there seems to be no operation to limit the number of points for the Modelnet dataset.

**Comment by Gofinge** [comment]
Yes, our code focuses more on real-world scene-level point clouds and we just simply test our performance on ModelNet40 without too much tuning. You can add a point number limitation in `transform.py` or `modelnet40.py`, which might lead to better performance since 10000 points are too redundant for ModelNet40.
