### ISSUE TITLE
Questions about VectorAttention

### ISSUE THREAD

**Issue by KinyoungWong** [Gofinge/PointTransformerV2#17]
Many thanks 4 ur repository!
I have a question about the VectorAttention:
You use subtraction relation of query and key into an attention weight in this code, I wonder what else relation function can do this too? Is there any advantage of subtraction operation?

One more thing, how should  I do to transform VectorAttention into Cross-Attention? I mean the input are two different pointclouds.

**Comment by Gofinge** [comment]
Hi, thanks for being interested in our work. 
About the **first** question, in PTv1 and SAN both subtraction (-), sum (+), element-wise product (*) and even matrix product (x) are relation functions, while in PTv2 we limited it to an element-wise operator (e.g., +, -, *) to extend to MSA. Normally there is not much difference between each relation encoding, while when we change Linear q and Linear k to a Linear-Norm-Act layer instead of a single Linear, subtraction relation encoding has a better performance.

About the **second** question, here is a simple pseudocode example a directly write on the issue page. 

``` python
# feat1, coord1, offset1: query point cloud
# feat2, coord2, offset2: reference point cloud (provide k, v)
# for reference_index
reference_index, _ = pointops.knn_query(self.neighbours,  coord2, offset2, coord1, offset1)

# class GroupedVectorAttention
    def forward(self, feat1, coord1, feat2, coord2, reference_index):
        query, key, value = self.linear_q(feat1), self.linear_k(feat2), self.linear_v(feat2)
        key = pointops.grouping(reference_index, key, coord, with_xyz=False)
        value = pointops.grouping(reference_index, value, coord, with_xyz=False)
        pos =  pointops.grouping(reference_index, coord2, coord, with_xyz=False) - coord
        .......
        return feat
```
