### ISSUE TITLE
Model weights of PTv2m1

### ISSUE THREAD

**Issue by chrockey** [Gofinge/PointTransformerV2#20]
Hi,

Thank you for releasing the source code of your excellent work :)
Could you provide the model weights of PTv2m1, which is used for [the camera-ready version of your paper](https://openreview.net/pdf?id=I3mLa12s_H) on either S3DIS or ScanNetV2?

**Comment by Gofinge** [comment]
Hi, thank you for being interested in our work. Due to a change in internship, we no longer have access to the weights that were trained in the first half of last year. Additionally, the released model code has been completely rewritten from the prototype code to make it easier to understand, making it incompatible with the original weights. At the moment, we do not have access to computing resources that contain 4 x 48G memory GPUs. However, we will share a PTv2m1 training log as soon as these computing resources become available.

**Comment by Gofinge** [comment]
Repeating 2-3 times should have a higher performance than I reported. PTv2m2 is also well worth trying.
