### ISSUE TITLE
About Reproduce Results on S3DIS

### ISSUE THREAD

**Issue by Rongtao-Xu** [Gofinge/PointTransformerV2#22]
Thank you for your awesome work!
I did not change the original code, and my best mIOU reproduction result on S3DIS val is 68.2, which is inconsistent with the official result 70.8. Do I need to change the settings on the original code or change some hyperparameters, specifically which hyperparameters? As you mentioned in GitHub, the original S3DIS data contains some bugs data need manually fix it. How can I fix it specifically? Can you provide code or a more detailed explanation?
Thanks a lot! Sincere appreciation to you for your great help!

**Comment by Gofinge** [comment]
Hi, have you tried test.py? The val mIoU reported in the training process is evaluated on the validation point cloud after voxelization. Since the S3DIS grid size is pretty large (0.05m), the accuracy is usually low than the precise test in test.py. 

Also, the discussion in issue #11 might be helpful, the training process is not stable on S3DIS, and a good choice is running more time and choosing the best to test. (My released val mIoU in the train process is about 70%, and val mIoU in the test process in 72.6%)

**Comment by Rongtao-Xu** [comment]
Thanks
